name: Build and Deploy to EC2

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build and tag Docker image
      run: |
        sudo docker build -t chairamama-website:latest .
        sudo docker save chairamama-website:latest | gzip > chairamama-website.tar.gz

    - name: Transfer Docker image to EC2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.HOST }}

      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H "$HOST" >> ~/.ssh/known_hosts

        scp -i ~/.ssh/id_rsa -P 22 chairamama-website.tar.gz ubuntu@$HOST:/tmp || exit 1  # Exit if scp fails

    - name: Deploy to EC2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.HOST }}

      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H "$HOST" >> ~/.ssh/known_hosts

        # SSH commands to run on EC2
        ssh -i ~/.ssh/id_rsa ubuntu@$HOST '
          cd /tmp &&
          sudo docker load < chairamama-website.tar.gz || exit 1  # Exit if Docker load fails
          sudo docker stop chairamama-website || true
          sudo docker rm chairamama-website || true
          sudo docker run -d --name chairamama-website -p 2024:3000 chairamama-website:latest || exit 1  # Exit if Docker run fails
        '
