name: Build and Deploy to EC2

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and tag Docker image
        run: |
          docker build -t chairamama-website:latest .
      
      - name: Save Docker image to tarball
        run: |
          docker save chairamama-website:latest | gzip > chairamama-website.tar.gz

      - name: Transfer Docker image to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            mkdir -p /tmp
            scp -i /tmp/ssh_key -P 22 chairamama-website.tar.gz ubuntu@${{ secrets.HOST }}:/tmp/chairamama-website.tar.gz || exit 1

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /tmp &&
            sudo docker load < chairamama-website.tar.gz || exit 1
            sudo docker stop chairamama-website || true
            sudo docker rm chairamama-website || true
            sudo docker run -d --name chairamama-website -p 2024:3000 chairamama-website:latest || exit 1
